import type {
  PrimaryActionsProps,
  RecordActionsProps,
  SettingsActionsProps,
  SubdomainActionsProps,
  UseDomainManagementFeatureProps,
} from './domainManagementFeatureTypes'
import { useDomainRecordActions } from './useDomainRecordActions'
import { useDomainSettingsActions } from './useDomainSettingsActions'
import { usePrimaryDomainActions } from './usePrimaryDomainActions'
import { useSubdomainActions } from './useSubdomainActions'

export function useDomainManagementActionHandlers(props: UseDomainManagementFeatureProps) {
  const primaryHandlers = usePrimaryDomainActions({
    appendActivity: props.appendActivity,
    canClearPrimary: props.canClearPrimary,
    canSetPrimary: props.canSetPrimary,
    displayName: props.displayName,
    nodeHex: props.nodeHex,
    primaryEndpoint: props.primaryEndpoint,
    runtimeConfig: props.runtimeConfig,
    selectedAuthority: props.selectedAuthority,
    setPrimaryEndpointValue: props.setPrimaryEndpointValue,
    setPrimaryError: props.setPrimaryError,
    setPrimaryName: props.setPrimaryName,
    setPrimaryTxState: props.setPrimaryTxState,
    shouldApplyPreviewWriteFallback: props.shouldApplyPreviewWriteFallback,
    submitNameWrite: props.submitNameWrite,
    walletSetupState: props.walletSetupState,
    ensureContractAuthorityForLiveWrite: props.ensureContractAuthorityForLiveWrite,
    ensurePublicBalanceForLiveWrite: props.ensurePublicBalanceForLiveWrite,
  } satisfies PrimaryActionsProps)

  const recordHandlers = useDomainRecordActions({
    activeRecordTarget: props.activeRecordTarget,
    appendActivity: props.appendActivity,
    canSaveRecords: props.canSaveRecords,
    criticalRecordChange: props.criticalRecordChange,
    nodeHex: props.nodeHex,
    recordBusy: props.recordBusy,
    recordDraftErrors: props.recordDraftErrors,
    recordDraftMutations: props.recordDraftMutations,
    runtimeConfig: props.runtimeConfig,
    selectedAddress: props.selectedAddress,
    selectedAuthority: props.selectedAuthority,
    setCriticalRecordConfirmation: props.setCriticalRecordConfirmation,
    setPrimaryEndpointValue: props.setPrimaryEndpointValue,
    setPublicRecordAcknowledged: props.setPublicRecordAcknowledged,
    setRecordDrafts: props.setRecordDrafts,
    setRecordError: props.setRecordError,
    setRecordTxState: props.setRecordTxState,
    setResolverRecordSets: props.setResolverRecordSets,
    shouldApplyPreviewWriteFallback: props.shouldApplyPreviewWriteFallback,
    submitNameWrite: props.submitNameWrite,
    walletAuthorized: props.walletAuthorized,
    walletSetupState: props.walletSetupState,
    ensureContractAuthorityForLiveWrite: props.ensureContractAuthorityForLiveWrite,
    ensurePublicBalanceForLiveWrite: props.ensurePublicBalanceForLiveWrite,
  } satisfies RecordActionsProps)

  const subdomainHandlers = useSubdomainActions({
    appendActivity: props.appendActivity,
    canCreateSubname: props.canCreateSubname,
    canDelegateSubname: props.canDelegateSubname,
    canRevokeSelectedSubname: props.canRevokeSelectedSubname,
    currentBlockHeight: props.currentBlockHeight,
    delegateManager: props.delegateManager,
    displayName: props.displayName,
    managedNameExpiresAt: props.managedName.expiresAt,
    nowSeconds: props.nowSeconds,
    runtimeConfig: props.runtimeConfig,
    selectedAddress: props.selectedAddress,
    selectedAuthority: props.selectedAuthority,
    selectedDelegatedSubname: props.selectedDelegatedSubname,
    setCriticalRecordConfirmation: props.setCriticalRecordConfirmation,
    setDelegateManager: props.setDelegateManager,
    setDelegateSubnameNode: props.setDelegateSubnameNode,
    setPublicRecordAcknowledged: props.setPublicRecordAcknowledged,
    setRecordDrafts: props.setRecordDrafts,
    setRecordError: props.setRecordError,
    setRecordTargetNode: props.setRecordTargetNode,
    setSubnameError: props.setSubnameError,
    setSubnames: props.setSubnames,
    setSubnameTxState: props.setSubnameTxState,
    shouldApplyPreviewWriteFallback: props.shouldApplyPreviewWriteFallback,
    submitNameWrite: props.submitNameWrite,
    walletSetupState: props.walletSetupState,
    subnameExpiryDate: props.subnameExpiryDate,
    subnameExpiryPolicy: props.subnameExpiryPolicy,
    subnameLabel: props.subnameLabel,
    subnameManager: props.subnameManager,
    subnameResolver: props.subnameResolver,
    subnameRevocationPolicy: props.subnameRevocationPolicy,
    ensureContractAuthorityForLiveWrite: props.ensureContractAuthorityForLiveWrite,
    ensurePublicBalanceForLiveWrite: props.ensurePublicBalanceForLiveWrite,
  } satisfies SubdomainActionsProps)

  const settingsHandlers = useDomainSettingsActions({
    appendActivity: props.appendActivity,
    canManageName: props.canManageName,
    canRenewName: props.canRenewName,
    currentBlockHeight: props.currentBlockHeight,
    displayName: props.displayName,
    draftManager: props.draftManager,
    draftOwner: props.draftOwner,
    feeConfig: props.feeConfig,
    lifecycleBaseBlockHeight: props.lifecycleBaseBlockHeight,
    managedName: props.managedName,
    nodeHex: props.nodeHex,
    nowSeconds: props.nowSeconds,
    renewalYears: props.renewalYears,
    resultLabel: props.resultLabel,
    runtimeConfig: props.runtimeConfig,
    selectedAuthority: props.selectedAuthority,
    setDraftManager: props.setDraftManager,
    setDraftOwner: props.setDraftOwner,
    setManagedName: props.setManagedName,
    setManagementError: props.setManagementError,
    setManagementTxState: props.setManagementTxState,
    setRenewalError: props.setRenewalError,
    setRenewalTxState: props.setRenewalTxState,
    shouldApplyPreviewWriteFallback: props.shouldApplyPreviewWriteFallback,
    submitNameWrite: props.submitNameWrite,
    walletSetupState: props.walletSetupState,
    ensureContractAuthorityForLiveWrite: props.ensureContractAuthorityForLiveWrite,
    ensurePublicBalanceForLiveWrite: props.ensurePublicBalanceForLiveWrite,
  } satisfies SettingsActionsProps)

  return {
    ...primaryHandlers,
    ...recordHandlers,
    ...settingsHandlers,
    ...subdomainHandlers,
  }
}
