import type { AppViewModelInputs } from '../appViewTypes'

export function buildRegistrationStateProps({
  domainRecordState,
  domainState,
  registrationState,
  searchState,
}: AppViewModelInputs) {
  const {
    commitTxState,
    committed,
    duration,
    preparedCommit,
    registerSetsPrimary,
    registrationAddressInput,
    registrationCompletion,
    registrationStep,
    setCommitTxState,
    setCommitted,
    setDuration,
    setPreparedCommit,
    setRegisterSetsPrimary,
    setRegistrationAddressInput,
    setRegistrationCompletion,
    setRegistrationStep,
    setTxState,
    txState,
  } = registrationState

  return {
    commitTxState,
    committed,
    duration,
    onBackToOverview: () => searchState.setResultView('overview'),
    onSetAddress: () => searchState.setResultView('details'),
    preparedCommit,
    registerSetsPrimary,
    registrationAddressInput,
    registrationCompletion,
    registrationStep,
    setCommitTxState,
    setCommitted,
    setCurrentBlockHeight: searchState.setCurrentBlockHeight,
    setDraftManager: domainState.setDraftManager,
    setDraftOwner: domainState.setDraftOwner,
    setDraftResolver: domainState.setDraftResolver,
    setDuration,
    setIndexerConfirmation: searchState.setIndexerConfirmation,
    setIndexerError: searchState.setIndexerError,
    setManagedName: domainState.setManagedName,
    setNowSeconds: searchState.setNowSeconds,
    setPreparedCommit,
    setPrimaryEndpointValue: domainState.setPrimaryEndpointValue,
    setPrimaryName: domainState.setPrimaryName,
    setRegisterSetsPrimary,
    setRegistrationAddressInput,
    setRegistrationCompletion,
    setRegistrationStep,
    setResolverRecordSets: domainRecordState.setResolverRecordSets,
    setTxState,
    showReservationRecovery: Boolean(committed && preparedCommit),
    txState,
  }
}
