import type { UseSearchRuntimeArgs } from './useSearchRuntime'
import type { AppCoreRuntimes } from './useAppCoreRuntimes'
import type { NameWorkspaceRuntime } from './useNameWorkspaceRuntime'

export function buildSearchRuntimeArgs({ core, workspace }: {
  core: AppCoreRuntimes
  workspace: NameWorkspaceRuntime
}): UseSearchRuntimeArgs {
  const { appRuntime, domainState, registrationState, searchState, walletRuntime } = core
  const { activityFeed, domainRecordState, namePreview, registrationRuntime } = workspace

  return {
    chainId: appRuntime.runtimeConfig.chainId,
    currentBlockHeight: searchState.currentBlockHeight,
    displayName: namePreview.displayName,
    getCurrentBlockHeight: appRuntime.getCurrentBlockHeight,
    indexerClient: appRuntime.indexerClient,
    liveDuskDomainsApp: appRuntime.liveDuskDomainsApp,
    loadPendingReservations: registrationRuntime.loadPendingReservations,
    nowSeconds: searchState.nowSeconds,
    openSearchView: () => searchState.setMainView('search'),
    query: searchState.query,
    recordSourceContractId: appRuntime.recordSourceContractId,
    selectedAuthority: walletRuntime.selectedAuthority,
    setActivityEntries: activityFeed.setActivityEntries,
    setActivityLoading: activityFeed.setActivityLoading,
    setApiSearchResult: searchState.setApiSearchResult,
    setChecked: searchState.setChecked,
    setCommitTxState: registrationState.setCommitTxState,
    setCommitted: registrationState.setCommitted,
    setConfirmationInput: domainState.setConfirmationInput,
    setCriticalRecordConfirmation: domainRecordState.setCriticalRecordConfirmation,
    setCurrentBlockHeight: searchState.setCurrentBlockHeight,
    setDelegateManager: domainState.setDelegateManager,
    setDelegateSubnameNode: domainState.setDelegateSubnameNode,
    setDuration: registrationState.setDuration,
    setDraftManager: domainState.setDraftManager,
    setDraftOwner: domainState.setDraftOwner,
    setDraftResolver: domainState.setDraftResolver,
    setIndexerConfirmation: searchState.setIndexerConfirmation,
    setIndexerError: searchState.setIndexerError,
    setManagedName: domainState.setManagedName,
    setManagementError: domainState.setManagementError,
    setManagementTxState: domainState.setManagementTxState,
    setPrimaryEndpointValue: domainState.setPrimaryEndpointValue,
    setPrimaryError: domainState.setPrimaryError,
    setPrimaryName: domainState.setPrimaryName,
    setPrimaryTxState: domainState.setPrimaryTxState,
    setPreparedCommit: registrationState.setPreparedCommit,
    setPublicRecordAcknowledged: domainRecordState.setPublicRecordAcknowledged,
    setQuery: searchState.setQuery,
    setRecordDrafts: domainRecordState.setRecordDrafts,
    setRecordError: domainState.setRecordError,
    setRecordTargetNode: domainRecordState.setRecordTargetNode,
    setRecordTxState: domainState.setRecordTxState,
    setRegisterSetsPrimary: registrationState.setRegisterSetsPrimary,
    setRegistrationAddressInput: registrationState.setRegistrationAddressInput,
    setRegistrationCompletion: registrationState.setRegistrationCompletion,
    setRegistrationStep: registrationState.setRegistrationStep,
    setRenewalError: domainState.setRenewalError,
    setRenewalTxState: domainState.setRenewalTxState,
    setRenewalYears: domainState.setRenewalYears,
    setResolverRecordSets: domainRecordState.setResolverRecordSets,
    setResultView: searchState.setResultView,
    setSubnameError: domainState.setSubnameError,
    setSubnameExpiryDate: domainState.setSubnameExpiryDate,
    setSubnameExpiryPolicy: domainState.setSubnameExpiryPolicy,
    setSubnameLabel: domainState.setSubnameLabel,
    setSubnameManager: domainState.setSubnameManager,
    setSubnameResolver: domainState.setSubnameResolver,
    setSubnameRevocationPolicy: domainState.setSubnameRevocationPolicy,
    setSubnameTxState: domainState.setSubnameTxState,
    setSubnames: domainState.setSubnames,
    setTxState: registrationState.setTxState,
  }
}
